<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="parrot" failures="1" tests="4" name="Surefire test" time="58.49" errors="0" timestamp="2025-02-03T21:41:25 IST">
  <testcase classname="com.mycompany.cynthia_onboardTest" name="test3_cynthiaOnboard" time="37.407"/>
  <testcase classname="com.mycompany.getautoassuredTest" name="test4_autoAssuredLogin" time="2.188"/>
  <testcase classname="com.mycompany.omniappTest" name="test2_invalidLogin" time="9.278"/>
  <testcase classname="com.mycompany.omniappTest" name="test1_validLogin" time="8.697">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.mycompany.omniappTest.test1_validLogin(omniappTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test1_validLogin -->
</testsuite> <!-- Surefire test -->
